# This is a basic workflow to help you get started with Actions

name: Lint

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Foreman
        uses: Roblox/setup-foreman@v1
        with:
            version: "^1.0.0"
            token: ${{ SECRETS.GITHUB_TOKEN }}
      - name: Lint
        run: |
          selene ./
